#!/usr/bin/env node

/**
 * LinkedIn Job Scraper - Setup Script
 * Automates the installation and configuration process
 */

const fs = require('fs').promises;
const path = require('path');
const { spawn } = require('child_process');
const readline = require('readline');

class SetupScript {
    constructor() {
        this.rl = readline.createInterface({
            input: process.stdin,
            output: process.stdout
        });
    }

    async run() {
        console.log('🚀 LinkedIn Job Scraper - Setup Script\n');
        console.log('This script will help you set up the LinkedIn Job Scraper application.\n');

        try {
            await this.checkPrerequisites();
            await this.installDependencies();
            await this.setupPlaywright();
            await this.configureEnvironment();
            await this.testSetup();
            
            console.log('\n✅ Setup completed successfully!');
            console.log('\n📋 Next steps:');
            console.log('   1. Get your Gemma API key from: https://makersuite.google.com/app/apikey');
            console.log('   2. Add it to your .env file');
            console.log('   3. Run: npm start');
            console.log('   4. Open: http://localhost:5000\n');
            
        } catch (error) {
            console.error('\n❌ Setup failed:', error.message);
            process.exit(1);
        } finally {
            this.rl.close();
        }
    }

    async checkPrerequisites() {
        console.log('🔍 Checking prerequisites...');
        
        // Check Node.js version
        const nodeVersion = process.version;
        const majorVersion = parseInt(nodeVersion.split('.')[0].substring(1));
        
        if (majorVersion < 16) {
            throw new Error(`Node.js 16+ required. Current version: ${nodeVersion}`);
        }
        
        console.log(`   ✓ Node.js ${nodeVersion}`);
        
        // Check npm
        try {
            await this.runCommand('npm', ['--version']);
            console.log('   ✓ npm installed');
        } catch (error) {
            throw new Error('npm is not installed or not accessible');
        }
    }

    async installDependencies() {
        console.log('\n📦 Installing dependencies...');
        
        try {
            await this.runCommand('npm', ['install'], { 
                stdio: 'pipe',
                showOutput: true 
            });
            console.log('   ✓ Dependencies installed');
        } catch (error) {
            throw new Error('Failed to install dependencies');
        }
    }

    async setupPlaywright() {
        console.log('\n🎭 Setting up Playwright browsers...');
        
        try {
            await this.runCommand('npx', ['playwright', 'install'], { 
                stdio: 'pipe',
                showOutput: true 
            });
            console.log('   ✓ Playwright browsers installed');
        } catch (error) {
            console.log('   ⚠️ Playwright setup failed, but you can install it manually later');
            console.log('      Run: npx playwright install');
        }
    }

    async configureEnvironment() {
        console.log('\n⚙️ Configuring environment...');
        
        const envPath = path.join(process.cwd(), '.env');
        const envExists = await this.fileExists(envPath);
        
        if (envExists) {
            console.log('   ✓ .env file already exists');
            return;
        }

        // Create .env from template
        const envTemplate = `# LinkedIn Job Scraper - Environment Variables
# Generated by setup script on ${new Date().toISOString()}

# Server Configuration
PORT=5000
NODE_ENV=development

# Gemma AI Configuration (Required)
# Get your API key from: https://makersuite.google.com/app/apikey
GEMMA_API_KEY=

# LinkedIn Credentials (Optional - use with caution)
LINKEDIN_EMAIL=
LINKEDIN_PASSWORD=

# Scraping Configuration
SCRAPE_DELAY=2000
MAX_JOBS_PER_SEARCH=50
BROWSER_HEADLESS=true

# Rate Limiting
RATE_LIMIT_WINDOW_MS=900000
RATE_LIMIT_MAX_REQUESTS=100

# Features
ENABLE_EXPORT=true
ENABLE_BOOKMARKS=true
DEBUG_MODE=false
`;

        await fs.writeFile(envPath, envTemplate);
        console.log('   ✓ .env file created');
        console.log('     📝 Please edit .env and add your Gemma API key');
    }

    async testSetup() {
        console.log('\n🧪 Testing setup...');
        
        try {
            // Test if server starts (without actually running it)
            const serverPath = path.join(process.cwd(), 'server.js');
            const serverExists = await this.fileExists(serverPath);
            
            if (!serverExists) {
                throw new Error('server.js not found');
            }
            
            console.log('   ✓ Server file exists');
            
            // Check other critical files
            const criticalFiles = [
                'package.json',
                'public/index.html',
                'public/style.css',
                'public/script.js',
                'routes/jobs.js',
                'scraper/linkedinScraper.js',
                'ai/gemmaMatcher.js'
            ];
            
            for (const file of criticalFiles) {
                const filePath = path.join(process.cwd(), file);
                const exists = await this.fileExists(filePath);
                
                if (!exists) {
                    throw new Error(`Critical file missing: ${file}`);
                }
            }
            
            console.log('   ✓ All critical files present');
            
        } catch (error) {
            throw new Error(`Setup test failed: ${error.message}`);
        }
    }

    async runCommand(command, args, options = {}) {
        return new Promise((resolve, reject) => {
            const child = spawn(command, args, {
                stdio: options.stdio || 'pipe',
                shell: true,
                ...options
            });

            let output = '';
            let errorOutput = '';

            if (child.stdout) {
                child.stdout.on('data', (data) => {
                    output += data.toString();
                    if (options.showOutput) {
                        process.stdout.write(data);
                    }
                });
            }

            if (child.stderr) {
                child.stderr.on('data', (data) => {
                    errorOutput += data.toString();
                    if (options.showOutput) {
                        process.stderr.write(data);
                    }
                });
            }

            child.on('close', (code) => {
                if (code === 0) {
                    resolve(output);
                } else {
                    reject(new Error(`Command failed with code ${code}: ${errorOutput}`));
                }
            });

            child.on('error', (error) => {
                reject(error);
            });
        });
    }

    async fileExists(filePath) {
        try {
            await fs.access(filePath);
            return true;
        } catch {
            return false;
        }
    }

    prompt(question) {
        return new Promise((resolve) => {
            this.rl.question(question, resolve);
        });
    }
}

// Interactive setup
async function interactiveSetup() {
    const setup = new SetupScript();
    
    console.log('Would you like to run the automated setup? (y/n): ');
    const answer = await setup.prompt('');
    
    if (answer.toLowerCase() === 'y' || answer.toLowerCase() === 'yes') {
        await setup.run();
    } else {
        console.log('\nManual setup instructions:');
        console.log('1. npm install');
        console.log('2. npx playwright install');
        console.log('3. Copy .env.example to .env and configure');
        console.log('4. npm start\n');
        setup.rl.close();
    }
}

// Run setup if this file is executed directly
if (require.main === module) {
    interactiveSetup().catch(console.error);
}

module.exports = SetupScript;